name: AppImage

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "master", "qe3", "qe3_wf_test" ]
  pull_request:
    branches: [ "master", "qe3" ]

jobs:
  ubuntu-qe3:
    name: Qt 6.8 / Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup CMake
        uses: ./.github/actions/cmake
        with:
          qt_version: 6.8.0
          use_qt6: ON
          modules: qtserialport qtmultimedia
          additional_cmake_args: -DCMAKE_INSTALL_PREFIX='${{ github.workspace }}/install/usr'

      - name: Create AppImage
        uses: ./.github/actions/appimage

